# Generated by Django 5.0.6 on 2024-07-06 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_libraryvisitor_visitor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
            preserve_default=False,
        ),
    ]
