# Generated by Django 5.0.6 on 2024-07-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='borrower',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrower_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
